-- ============================================================
-- REVIEWS TABLE — DATABASE SETUP
-- File: DATABASE_SETUP_REVIEWS.sql
-- Run this in your Supabase Dashboard → SQL Editor
-- ============================================================
--
-- FOR JUNIOR DEVELOPERS:
-- This file creates the `reviews` table in your Supabase PostgreSQL
-- database along with indexes (for fast queries) and Row Level Security
-- (RLS) policies (so users can only modify their OWN data).
--
-- HOW TO RUN:
--   1. Open https://supabase.com → Your project
--   2. Click "SQL Editor" in the left sidebar
--   3. Paste this entire file and click "Run"
--   4. Verify by running: SELECT * FROM reviews LIMIT 5;
--
-- TABLE STRUCTURE:
--   - id            → UUID primary key (auto-generated by Supabase)
--   - product_id    → FakeStore API product number (e.g. 1, 2, 3…)
--   - user_id       → References the user in Supabase auth.users
--   - author_name   → Snapshot of display name at submission time
--   - author_avatar → Snapshot of avatar URL (nullable)
--   - rating        → 1 to 5 stars
--   - title         → Short headline (max 80 chars)
--   - body          → Full review text (max 2000 chars)
--   - created_at    → When first submitted (auto-set)
--   - updated_at    → When last edited (updated by trigger)
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- STEP 1: CREATE THE TABLE
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS reviews (
  -- UUID primary key — Supabase generates this automatically
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Links to a FakeStore API product by its numeric ID
  -- NOT a foreign key because products live in an external API, not our DB
  product_id     INTEGER NOT NULL,

  -- Links to the Supabase auth user who wrote this review
  -- ON DELETE CASCADE: if the user account is deleted, their reviews go too
  user_id        UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Snapshot of the author's display name at the time of submission
  -- Stored here so the review still shows a name even if the user
  -- later changes their display name or deletes their account
  author_name    TEXT NOT NULL DEFAULT 'Anonymous',

  -- Nullable: not all users have an avatar
  author_avatar  TEXT,

  -- Star rating: must be 1, 2, 3, 4, or 5
  rating         SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),

  -- Short review headline (e.g. "Great quality for the price!")
  title          TEXT NOT NULL CHECK (char_length(title) BETWEEN 1 AND 80),

  -- Full review body text
  body           TEXT NOT NULL CHECK (char_length(body) BETWEEN 10 AND 2000),

  -- Timestamps — created_at is set once on INSERT; updated_at changes on UPDATE
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- UNIQUE constraint: one review per user per product
  -- This is what makes the upsert in reviews.service.ts work.
  -- If a (product_id, user_id) pair already exists, the upsert updates it
  -- instead of inserting a duplicate.
  CONSTRAINT reviews_user_product_unique UNIQUE (product_id, user_id)
);

-- ─────────────────────────────────────────────────────────────
-- STEP 2: CREATE INDEXES FOR FAST QUERIES
-- ─────────────────────────────────────────────────────────────

-- Index: fetch all reviews for a product quickly
-- Used by: getReviewsForProduct(productId)
CREATE INDEX IF NOT EXISTS idx_reviews_product_id
  ON reviews (product_id);

-- Index: fetch a specific user's reviews quickly
-- Used by: getUserReviewForProduct(productId, userId)
CREATE INDEX IF NOT EXISTS idx_reviews_user_id
  ON reviews (user_id);

-- Index: sort by newest first efficiently
-- Used by: ORDER BY created_at DESC
CREATE INDEX IF NOT EXISTS idx_reviews_created_at
  ON reviews (created_at DESC);

-- ─────────────────────────────────────────────────────────────
-- STEP 3: AUTO-UPDATE `updated_at` ON EDIT
-- ─────────────────────────────────────────────────────────────

-- This function is called by the trigger below.
-- It sets updated_at to NOW() every time a row is updated.
-- This means the service doesn't need to manually pass updated_at.
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger: runs before any UPDATE on the reviews table
CREATE TRIGGER reviews_updated_at
  BEFORE UPDATE ON reviews
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ─────────────────────────────────────────────────────────────
-- STEP 4: ENABLE ROW LEVEL SECURITY (RLS)
-- ─────────────────────────────────────────────────────────────
--
-- RLS policies are the security layer. Without them, any authenticated
-- user could read, edit, or delete anyone's reviews via the API.
--
-- With RLS:
--   - ANYONE can READ reviews (even logged-out visitors)
--   - Only the AUTHOR can INSERT/UPDATE/DELETE their own reviews

-- Enable RLS on the table (locks it down by default)
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

-- Policy 1: Everyone can read all reviews
-- This allows the product page to show reviews to all visitors
CREATE POLICY "reviews_read_public"
  ON reviews
  FOR SELECT
  USING (true); -- true = no restriction on reads

-- Policy 2: Authenticated users can insert their own reviews
-- auth.uid() is a Supabase function that returns the current user's UUID
CREATE POLICY "reviews_insert_own"
  ON reviews
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Policy 3: Users can update only THEIR OWN reviews
CREATE POLICY "reviews_update_own"
  ON reviews
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Policy 4: Users can delete only THEIR OWN reviews
CREATE POLICY "reviews_delete_own"
  ON reviews
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────
-- STEP 5: SEED DATA (optional — for testing)
-- ─────────────────────────────────────────────────────────────
--
-- Uncomment the INSERT below to add sample reviews for testing.
-- Replace 'YOUR-USER-UUID-HERE' with a real UUID from your
-- Supabase Dashboard → Authentication → Users.
--
-- INSERT INTO reviews (product_id, user_id, author_name, rating, title, body)
-- VALUES
--   (1, 'YOUR-USER-UUID-HERE', 'Test User', 5, 'Absolutely love this!',
--    'Ordered this for my daily commute and it holds everything I need. Very happy with the quality and the stitching looks durable.'),
--   (1, 'YOUR-USER-UUID-HERE', 'Test User', 4, 'Great bag, minor issues',
--    'Love the design and the material feels premium. The zipper is a little stiff at first but loosened up after a week of use.');

-- ─────────────────────────────────────────────────────────────
-- VERIFICATION QUERIES
-- ─────────────────────────────────────────────────────────────
-- Run these to confirm everything was created correctly:
--
--   SELECT table_name FROM information_schema.tables WHERE table_name = 'reviews';
--   SELECT * FROM reviews LIMIT 5;
--   SELECT schemaname, tablename, policyname FROM pg_policies WHERE tablename = 'reviews';
